# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_studies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="casestudy",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="case_studies/"),
        ),
    ]
