# Generated by Django 6.0.2 on 2026-03-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0002_casestudy_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Case study', 'verbose_name_plural': 'Case studies'},
        ),
        migrations.AlterModelOptions(
            name='engineeringdecision',
            options={'ordering': ['id'], 'verbose_name': 'Engineering decision', 'verbose_name_plural': 'Engineering decisions'},
        ),
        migrations.AddField(
            model_name='casestudy',
            name='content_es',
            field=models.TextField(blank=True, verbose_name='Content (Spanish)'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='summary_es',
            field=models.TextField(blank=True, verbose_name='Summary (Spanish)'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='engineeringdecision',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='engineeringdecision',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='engineeringdecision',
            name='tradeoffs_es',
            field=models.TextField(blank=True, verbose_name='Tradeoffs (Spanish)'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='case_studies/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='metrics',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metrics'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='summary',
            field=models.TextField(verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='engineeringdecision',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='engineeringdecision',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='engineeringdecision',
            name='tradeoffs',
            field=models.TextField(blank=True, verbose_name='Tradeoffs'),
        ),
    ]
