# Generated by Django 6.0.2 on 2026-03-08 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0003_add_spanish_content_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='content_es',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='summary_es',
            field=models.TextField(blank=True, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='engineeringdecision',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='engineeringdecision',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='engineeringdecision',
            name='tradeoffs_es',
            field=models.TextField(blank=True, verbose_name='Tradeoffs'),
        ),
        migrations.CreateModel(
            name='CaseStudyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='case_studies/gallery/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='case_studies.casestudy')),
            ],
            options={
                'verbose_name': 'Case study image',
                'verbose_name_plural': 'Case study images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
