# Generated by Django 6.0.2 on 2026-03-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_studies', '0007_add_structured_content_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='adrs',
            field=models.JSONField(blank=True, default=list, help_text='Architecture Decision Records links. Shown if you add an ADR block to the project page. JSON: [{"title":"","href":""}]', verbose_name='ADRs'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='ascii_diagram',
            field=models.TextField(blank=True, help_text='Optional ASCII diagram shown under the overview text on the project page.', verbose_name='ASCII diagram'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='deep_dive',
            field=models.JSONField(blank=True, default=list, help_text='Shown in the «Deep dive» section when the site is in English. JSON: [{"title":"","paragraphs":["",...]}]', verbose_name='Deep dive (EN)'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='deep_dive_es',
            field=models.JSONField(blank=True, default=list, help_text='Same structure as EN. Shown when the site is in Spanish.', verbose_name='Deep dive (ES)'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='diagram_type',
            field=models.CharField(blank=True, help_text='Defines which diagram is shown in the «Architecture & Design» section: use "payments" or "identity". Leave empty to use the value from static content.', max_length=32, verbose_name='Diagram type'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='rejected_approaches',
            field=models.JSONField(blank=True, default=list, help_text='Shown in the «What was explicitly rejected» section when the site is in English. JSON: [{"approach":"","reason":""}]', verbose_name='Rejected approaches (EN)'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='rejected_approaches_es',
            field=models.JSONField(blank=True, default=list, help_text='Same structure as EN. Shown when the site is in Spanish.', verbose_name='Rejected approaches (ES)'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='scale_constraints',
            field=models.JSONField(blank=True, default=dict, help_text='Shown in the «Scale & Constraints» section when the site is in English. JSON: {"requestVolume":"","concurrency":"","externalDependencies":"","failureModes":"","dataConsistency":""}', verbose_name='Scale constraints (EN)'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='scale_constraints_es',
            field=models.JSONField(blank=True, default=dict, help_text='Same structure as EN. Shown when the site is in Spanish.', verbose_name='Scale constraints (ES)'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='what_would_break',
            field=models.JSONField(blank=True, default=list, help_text='Shown in the «What would break this system?» section when the site is in English. JSON: ["string", ...]', verbose_name='What would break (EN)'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='what_would_break_es',
            field=models.JSONField(blank=True, default=list, help_text='Same structure as EN. Shown when the site is in Spanish.', verbose_name='What would break (ES)'),
        ),
    ]
