# Generated by Django 6.0.2 on 2026-03-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Decision',
                'verbose_name_plural': 'Selected engineering decisions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeepDiveEssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('paragraphs', models.TextField(help_text='Un párrafo por línea. Las líneas vacías se mantienen.')),
            ],
            options={
                'verbose_name': 'Deep dive essay',
                'verbose_name_plural': 'Architecture & Design (deep dive)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExecutiveSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Executive snapshot (viñeta)',
                'verbose_name_plural': 'Executive snapshot',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(help_text='Ej: patagoniadreams.com.ar — reservation availability', max_length=255)),
                ('challenge', models.TextField()),
                ('decision', models.TextField()),
                ('impact', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Experience summary (fila)',
                'verbose_name_plural': 'Experience summary',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OptimizeFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Optimize for',
                'verbose_name_plural': 'What I Optimize For',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Principle',
                'verbose_name_plural': 'Engineering principles',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies & Integrations',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tradeoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=500)),
                ('gained', models.TextField()),
                ('sacrificed', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tradeoff',
                'verbose_name_plural': 'Explicit tradeoffs',
                'ordering': ['order', 'id'],
            },
        ),
    ]
