# Generated by Django 6.0.2 on 2026-03-07 19:36

from django.db import migrations


def fill_empty_paths(apps, schema_editor):
    PageView = apps.get_model("core", "PageView")
    PageView.objects.filter(path="").update(path="/")
    # Por si se guardó con espacios en blanco
    for pv in PageView.objects.all():
        if not pv.path or not pv.path.strip():
            pv.path = "/"
            pv.save(update_fields=["path"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_portfolio_content_models"),
    ]

    operations = [
        migrations.RunPython(fill_empty_paths, noop),
    ]
