# Generated by Django 6.0.2 on 2026-03-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fill_empty_pageview_paths'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executivesnapshot',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Executive snapshot (bullet)', 'verbose_name_plural': 'Executive snapshot'},
        ),
        migrations.AlterModelOptions(
            name='experiencesummary',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Experience summary (row)', 'verbose_name_plural': 'Experience summary'},
        ),
        migrations.AddField(
            model_name='decision',
            name='text_es',
            field=models.TextField(blank=True, verbose_name='Text (Spanish)'),
        ),
        migrations.AddField(
            model_name='deepdiveessay',
            name='paragraphs_es',
            field=models.TextField(blank=True, verbose_name='Paragraphs (Spanish)'),
        ),
        migrations.AddField(
            model_name='deepdiveessay',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='executivesnapshot',
            name='text_es',
            field=models.CharField(blank=True, max_length=500, verbose_name='Text (Spanish)'),
        ),
        migrations.AddField(
            model_name='experiencesummary',
            name='challenge_es',
            field=models.TextField(blank=True, verbose_name='Challenge (Spanish)'),
        ),
        migrations.AddField(
            model_name='experiencesummary',
            name='decision_es',
            field=models.TextField(blank=True, verbose_name='Decision (Spanish)'),
        ),
        migrations.AddField(
            model_name='experiencesummary',
            name='impact_es',
            field=models.TextField(blank=True, verbose_name='Impact (Spanish)'),
        ),
        migrations.AddField(
            model_name='experiencesummary',
            name='scope_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Scope (Spanish)'),
        ),
        migrations.AddField(
            model_name='optimizefor',
            name='explanation_es',
            field=models.TextField(blank=True, verbose_name='Explanation (Spanish)'),
        ),
        migrations.AddField(
            model_name='optimizefor',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='principle',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description (Spanish)'),
        ),
        migrations.AddField(
            model_name='principle',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='technology',
            name='name_es',
            field=models.CharField(blank=True, max_length=120, verbose_name='Name (Spanish)'),
        ),
        migrations.AddField(
            model_name='tradeoff',
            name='decision_es',
            field=models.CharField(blank=True, max_length=500, verbose_name='Decision (Spanish)'),
        ),
        migrations.AddField(
            model_name='tradeoff',
            name='gained_es',
            field=models.TextField(blank=True, verbose_name='Gained (Spanish)'),
        ),
        migrations.AddField(
            model_name='tradeoff',
            name='sacrificed_es',
            field=models.TextField(blank=True, verbose_name='Sacrificed (Spanish)'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='read',
            field=models.BooleanField(default=False, verbose_name='read'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='deepdiveessay',
            name='paragraphs',
            field=models.TextField(help_text='One paragraph per line. Empty lines are preserved.', verbose_name='Paragraphs'),
        ),
        migrations.AlterField(
            model_name='deepdiveessay',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='executivesnapshot',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='executivesnapshot',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='experiencesummary',
            name='challenge',
            field=models.TextField(verbose_name='Challenge'),
        ),
        migrations.AlterField(
            model_name='experiencesummary',
            name='decision',
            field=models.TextField(verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='experiencesummary',
            name='impact',
            field=models.TextField(verbose_name='Impact'),
        ),
        migrations.AlterField(
            model_name='experiencesummary',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='experiencesummary',
            name='scope',
            field=models.CharField(help_text='E.g.: patagoniadreams.com.ar — reservation availability', max_length=255, verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='optimizefor',
            name='explanation',
            field=models.TextField(verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='optimizefor',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='optimizefor',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='path',
            field=models.CharField(max_length=500, verbose_name='path'),
        ),
        migrations.AlterField(
            model_name='principle',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='principle',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='principle',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='tradeoff',
            name='decision',
            field=models.CharField(max_length=500, verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='tradeoff',
            name='gained',
            field=models.TextField(verbose_name='Gained'),
        ),
        migrations.AlterField(
            model_name='tradeoff',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='tradeoff',
            name='sacrificed',
            field=models.TextField(verbose_name='Sacrificed'),
        ),
    ]
