# Generated by Django 6.0.2 on 2026-03-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_spanish_content_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='text_es',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='deepdiveessay',
            name='paragraphs_es',
            field=models.TextField(blank=True, verbose_name='Paragraphs'),
        ),
        migrations.AlterField(
            model_name='deepdiveessay',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='executivesnapshot',
            name='text_es',
            field=models.CharField(blank=True, max_length=500, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='experiencesummary',
            name='challenge_es',
            field=models.TextField(blank=True, verbose_name='Challenge'),
        ),
        migrations.AlterField(
            model_name='experiencesummary',
            name='decision_es',
            field=models.TextField(blank=True, verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='experiencesummary',
            name='impact_es',
            field=models.TextField(blank=True, verbose_name='Impact'),
        ),
        migrations.AlterField(
            model_name='experiencesummary',
            name='scope_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='optimizefor',
            name='explanation_es',
            field=models.TextField(blank=True, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='optimizefor',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='principle',
            name='description_es',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='principle',
            name='title_es',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name_es',
            field=models.CharField(blank=True, max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tradeoff',
            name='decision_es',
            field=models.CharField(blank=True, max_length=500, verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='tradeoff',
            name='gained_es',
            field=models.TextField(blank=True, verbose_name='Gained'),
        ),
        migrations.AlterField(
            model_name='tradeoff',
            name='sacrificed_es',
            field=models.TextField(blank=True, verbose_name='Sacrificed'),
        ),
    ]
